import { component$, Slot } from '@builder.io/qwik';
import {
  routeLoader$,
  type DocumentHead,
  type RequestHandler,
} from '@builder.io/qwik-city';
import { Navbar } from '~/components/ui/Navbar';
import { getPages } from '~/lib/sanity.queries';

export const onGet: RequestHandler = async ({ cacheControl }) => {
  // Control caching for this request for best performance and to reduce hosting costs:
  // https://qwik.builder.io/docs/caching/
  cacheControl({
    // Always serve a cached response by default, up to a week stale
    staleWhileRevalidate: 60 * 60 * 24 * 7,
    // Max once every 5 seconds, revalidate on the server to get a fresh version of this page
    maxAge: 5,
  });
};

export const usePages = routeLoader$(async () => {
  const pages = await getPages();

  return pages;
});

export default component$(() => {
  return (
    <>
      <Navbar />
      <Slot />
    </>
  );
});

export const head: DocumentHead = {
  title: 'My Awesome Site',
  meta: [
    {
      name: 'description',
      content: 'Generated by Qwik + Sanity',
    },
  ],
};
